---
title: "Access API"
author: "Jakob Richter"
date: "January 26, 2018"
output: html_document
---

## Build and start the container
```{r, engine='sh', eval = FALSE}
bash ../docker/rebuild-omlbotlookup.sh
bash ../docker/run-omlbotlookup.sh
```

## Accessing the API


```{r access}
library(jsonlite)
library(httr)
server.url = "http://localhost:8746"
```

### Ask for available Tasks
```{r tasks}
httr.res = GET(paste0(server.url, "/tasks"), accept_json())
content(httr.res)
```

### Ask for avaialble Algos for given Task
```{r algos}
httr.res = GET(paste0(server.url, "/algos"), query = list(task = 3), accept_json())
content(httr.res)
```

### Ask for needed params for given Algo
```{r param}
httr.res = GET(paste0(server.url, "/params"), query = list(algo = "classif.rpart"), accept_json())
content(httr.res)
```

### Lookup performance data for `algo` on `task` with some given paramters
```{r performance}
parameters = list(cp = 0.3, maxdepth = 10, minbucket = 3, minsplit = 10)
query = list(algo = "classif.rpart", task = 3, parameters = toJSON(parameters))
httr.res = GET(server.url, query = query, accept_json())
res = content(httr.res)
res

# We return the performance estimate for your setup.
performance = res[[1]]$performance

# We also return the euclidean distance to the nearest point in the database, so you know how certain we are.
distance = res[[1]]$distances

# If you want to examine the actual point yourself, we return the setup id and parameter values of the actual run as well.
nearest_setup = res[[1]][names(parameters)]
```

The query can be made for multiple settings
```{r performances}
parameters = list(cp = c(0.3, 0.7), maxdepth = c(10, 30), minbucket = c(3, 1), minsplit = c(10, 4))
query = list(algo = "classif.rpart", task = 3, parameters = toJSON(parameters))
httr.res = GET(server.url, query = query, accept_json())
res = content(httr.res)
do.call(rbind, res)
```
